// <auto-generated />
using DiarioDePesca.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DiarioDePesca.Migrations
{
    [DbContext(typeof(EspecieContext))]
    partial class EspecieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DiarioDePesca.Models.Especie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.Property<string>("NomeB");

                    b.Property<string>("NomeCientifico");

                    b.HasKey("Id");

                    b.ToTable("Especie");
                });
#pragma warning restore 612, 618
        }
    }
}
